Add a README with the instruction to run the TCK
eclipse/microprofile-reactive-streams-operators pull request #157
Opened 2021-02-01 16:08 UTC by cescoffier

@Emily-Jiang as discussed.

2021-02-01 16:12 UTC, genie-microprofile commented
Can one of the admins verify this patch?

2021-02-01 18:45 UTC, xstefank approved these changes

2021-02-01 18:54 UTC, Emily-Jiang requested changes
To make it consistent with others, can you add the following or something similar?

= Running the MicroProfile Reactive Streams Operators TCK

Any MicroProfile Reactive Streams Operators implementation must pass this test suite. The TCK uses `TestNG` and `Arquillian`.

== Hardware Requirements

All systems should meet the following recommended hardware requirements:

    * CPU running at 2.0 GHz or higher
    * 4 GB of RAM or more
    * Network access to the Internet

== Software Requirements

You can run MicroProfile Config TCK on platforms running the Solaris, Linux, Windows, and Mac OS with the following software installed:

    * Maven
    * JDK8+

2021-02-02 07:06 UTC, cescoffier commented
We don't use Arquillian to pass the TCK. That's an option. The provided instructions is what we are using.

2021-02-02 07:22 UTC, cescoffier commented
@Emily-Jiang Updated.

BTW, it's Apache Maven. Please fix it in MP Config.

2021-02-02 11:57 UTC, Emily-Jiang commented on tck/README.adoc
> +The TCK used TestNG.
```suggestion
The TCK uses TestNG.
```

2021-02-02 11:58 UTC, Emily-Jiang approved these changes
@cescoffier I made just one grammar change. Please accept it and merge your PR.

2021-02-02 12:21 UTC, merged