Updates readme file to add multiny as vendor option
eclipse/microprofile-reactive-streams-operators pull request #167
Opened 2021-05-24 15:39 UTC by otaviojava

2021-05-24 16:37 UTC, cescoffier requested changes

2021-05-24 16:37 UTC, cescoffier commented on README.adoc
> +* https://github.com/smallrye/smallrye-mutiny/tree/main/reactive-streams-operators[smallrye-mutiny] - based on Eclipse Vert.x.
Mutiny is not based on Vert.x.

2021-05-24 19:13 UTC, otaviojava commented on README.adoc
> +* https://github.com/smallrye/smallrye-mutiny/tree/main/reactive-streams-operators[smallrye-mutiny] - based on Eclipse Vert.x.
Thank you @cealsair fixed.

2021-05-25 05:41 UTC, cescoffier requested changes

2021-05-25 05:41 UTC, cescoffier commented on README.adoc
> +* https://github.com/smallrye/smallrye-mutiny/tree/main/reactive-streams-operators[smallrye-mutiny]
Sorry to be picky, it should be:

```suggestion
* https://github.com/smallrye/smallrye-mutiny/tree/main/reactive-streams-operators[Reactive Streams Operators implementation based on SmallRye Mutiny]
```

Mutiny is more than an implementation of the specification. Actually, this implementation is only there to let us implement Reactive Messaging.

2021-05-25 10:29 UTC, otaviojava commented
@cescoffier thank you for the suggestion.

2021-05-25 12:57 UTC, cescoffier approved these changes

2021-05-25 12:57 UTC, merged

2021-05-25 12:57 UTC, cescoffier commented
Thanks!